### PR TITLE
salad is done

### PR DESCRIPTION
**Pull request by TegzoK**

### CODE REVIEW

**Comment by IrinaPK8** [comment]
great salad!

**Comment by SF001User** [comment]
gret salad indeed

**Comment by Ahmadsabawoon** [comment]
Great salad

**Review by Ahmadsabawoon — APPROVED** [review]

**Review by SF001User — APPROVED** [review]
This is great salad can we add more cucumber though ? 
actually enough cucumber , lets do the thing to merge

**Pull request merged**
