### PR TITLE
tc2-alihan

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by TegzoK — APPROVED** [review]

**Review by SF001User — CHANGES_REQUESTED** [review]
can we do this and that instead ?

**Comment by johnnyone-github** [comment]
ok

**Review by ghost — COMMENTED** [review]
reviewed. nice code Kinga!

**Review by johnnyone-github — APPROVED** [review]
good

**Review by lo-guliko — APPROVED** [review]
cool beans

**Review by johnnyone-github — APPROVED** [review]
nice code

**Review by TegzoK — APPROVED** [review]

**Review by ghost — COMMENTED** [review]
//

**Pull request closed without merging**
